---
- name: Open internal ports for database servers
  firewalld:
    zone: internal
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  loop:
    - "22"    # SSH
    - "3306"  # MySQL
    - "9100"  # Node exporter