Vagrant.configure("2") do |config|
  # Общие настройки
  # Отключаем проврку обновления box и guest-addition
  config.vm.box_check_update = false
  config.vbguest.no_install = true

  # ===== Update kernel-arm =====
  # Конфигурация виртуальной машины
  config.vm.define "selinx" do |selinux|
    selinux.vm.box = "generic/rocky9"
    selinux.vm.box_version = "4.3.12"
    # selinux.vm.hostname = "selinux"
    selinux.vm.synced_folder ".", "/vagrant", disabled: false
    selinux.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "Otus-learn_15"
    end
    # Выполняем послеустановочные скрипты
     selinux.vm.provision "shell", inline: <<-SHELL
      yum install -y epel-release
      yum install -y nginx
      yum install -y setroubleshoot-server selinux-policy-mls setools-console policycoreutils-python-utils policycoreutils-newrole
      sed -ie 's/:80/:8080/g' /etc/nginx/nginx.conf
      sed -i 's/listen       80;/listen       8080;/' /etc/nginx/nginx.conf
      systemctl start nginx
      systemctl status nginx
      ss -tlpn | grep 4881
SHELL
  end
end
