---
- name: Deploy and configure Nginx on CentOS 7
  hosts: all
  become: yes
  vars_files:
    - vars/default.yml # Файл с переменными

  tasks:
    - name: Install EPEL repository (required for nginx on CentOS 7)
    # Для установки ngix нужен epel репозиторий
      yum:
        name: epel-release
        state: present

    - name: Install packages
    # Устаннавливаем nginx и пакеты для управления SELinux
      yum:
        name:
          - nginx
          - policycoreutils-python
          - policycoreutils-newrole
        state: latest
      notify:
        - Enable nginx service
        - Start nginx service

    - name: Create custom nginx configuration from template
    # Разворачиваем конфигурацию из шаблона jinja2 с перемененными;
      template:
        src: templates/nginx.conf.j2
        dest: "{{ nginx_conf_path }}"
        backup: yes
        mode: 0644

    - name: Add SELinux port permission for nginx on port 8080
    # Настраиваем SELinux (привет предыдущей лабораторке )
      seport:
        ports: "{{ nginx_listen_port }}"
        proto: tcp
        setype: http_port_t
        state: present

      notify:
        - Enable nginx service # Добавляем nginx в автозагрузку
        - Start nginx service  # Стартуем nginx

    - name: Configure firewall to allow nginx port
     # Настраиваем Firewall
      firewalld:
        port: "{{ nginx_listen_port }}/tcp"
        permanent: yes
        state: enabled
      notify:
        - Reload firewall

    - name: Create custom index.html
    # Создадим свой index.html, который будет показывать информацию о настроках
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Nginx on Port {{ nginx_listen_port }}</title>
          </head>
          <body>
              <h1>Welcome to Nginx!</h1>
              <p>Server is listening on port {{ nginx_listen_port }}</p>
              <p>This page was deployed by Ansible</p>
              <p>SELinux configured for port {{ nginx_listen_port }}</p>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html
        mode: 0644

  handlers:
    - name: Enable nginx service
      systemd:
        name: nginx
        enabled: yes

    - name: Start nginx service
      systemd:
        name: nginx
        state: started

    - name: Reload firewall
      systemd:
        name: firewalld
        state: reloaded