# roles/common/tasks/main.yml
---
# Добавление EPEL репозитория
- name: Install EPEL repository 
  ansible.builtin.dnf:
    name: epel-release
    state: present


# Установка основных пакетов
- name: Install basic packages 
  ansible.builtin.dnf:
    name:
      - vim
      - nano
      - curl
      - wget
      - htop
      - git
      - policycoreutils-python-utils  # ← ДОБАВИТЬ для SELinux управления
      - libselinux-python3
    state: present

# Установка node-exporter на все сервера, кроме mon-srv
- name: Install node-exporter (except monitoring server)
  ansible.builtin.dnf:
    name: node-exporter
    state: present
  when: inventory_hostname != "mon-srv"

# настройка хранения journald логов
- name: Configure journald to persist logs to disk 
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?Storage="
    line: "Storage=persistent"
    backup: yes

- name: Create journal directory 
  file:
    path: /var/log/journal
    state: directory
    owner: root
    group: systemd-journal
    mode: '0755'

- name: Add promtail user to systemd-journal group
  user:
    name: promtail
    groups: systemd-journal
    append: yes

- name: Restart systemd-journald to apply changes
  systemd:
    name: systemd-journald
    state: restarted

- name: Start and enable node-exporter service
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes
  when: inventory_hostname != "mon-srv"  # ← ИСКЛЮЧАЕМ mon-srv

# Включаем Firewall
- name: Ensure firewalld is started and enabled 
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

# Настраиваем Selinux в состояние enforcing
- name: Ensure SELinux is enforcing 
  ansible.builtin.selinux:
    policy: targeted
    state: enforcing
  register: selinux_result

- name: Reboot the system if required (e.g., after SELinux change)
  ansible.builtin.reboot:
    msg: "Reboot triggered by Ansible for SELinux"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: selinux_result.changed
  async: 1
  poll: 0

# Распространяем изменения в фай hosts на все сервера
- name: Add internal DNS entries to hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      # Internal network hosts
      192.168.56.10 web-srv web-srv.internal
      192.168.56.11 db-1-srv db-1-srv.internal
      192.168.56.12 db-2-srv db-2-srv.internal
      192.168.56.13 mon-srv mon-srv.internal
      192.168.56.14 ansible-srv ansible-srv.internal
    marker: "# {mark} ANSIBLE MANAGED - INTERNAL HOSTS"
