- name: Fix replication after master restore from slave backup
  hosts: databases
  become: yes
  vars:
    primary_host: "db-1-srv"
    replica_host: "db-2-srv"
  
  tasks:
    - name: Stop replication on replica via SQL
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        query: "STOP SLAVE"
      when: inventory_hostname == replica_host
      delegate_to: "{{ replica_host }}"

    - name: Get current master positions
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        query: "SHOW MASTER STATUS"
      register: new_master_status
      delegate_to: "{{ primary_host }}"
      run_once: true

    - name: Extract master positions with correct path
      set_fact:
        master_log_file: "{{ new_master_status.query_result[0][0]['File'] }}"
        master_log_pos: "{{ new_master_status.query_result[0][0]['Position'] }}"
      run_once: true

    - name: Debug extracted positions
      debug:
        msg: |
          Master Log File: {{ master_log_file }}
          Master Log Position: {{ master_log_pos }}
      run_once: true

    - name: Reset replication via SQL
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        query: "RESET SLAVE ALL"
      when: inventory_hostname == replica_host
      delegate_to: "{{ replica_host }}"

    - name: Configure replication via SQL
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        query: |
          CHANGE MASTER TO
          MASTER_HOST='{{ primary_host }}',
          MASTER_USER='{{ mariadb_replication_user }}',
          MASTER_PASSWORD='{{ mariadb_replication_password }}',
          MASTER_LOG_FILE='{{ master_log_file }}',
          MASTER_LOG_POS={{ master_log_pos }}
      when: inventory_hostname == replica_host
      delegate_to: "{{ replica_host }}"

    - name: Start replication via SQL
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        query: "START SLAVE"
      when: inventory_hostname == replica_host
      delegate_to: "{{ replica_host }}"

    - name: Verify tables exist on replica
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        query: "SHOW TABLES IN project_db"
      when: inventory_hostname == replica_host
      register: replica_tables
      delegate_to: "{{ replica_host }}"

    - name: Show replication result
      debug:
        msg: |
          Replication configured successfully!
          Master: {{ master_log_file }}:{{ master_log_pos }}
          Tables on replica: {{ replica_tables.query_result | length }}
      when: inventory_hostname == replica_host