Vagrant.configure("2") do |config|
  # Общие настройки
  # Отключаем проврку обновления box и guest-addition
  config.vm.box_check_update = false
  config.vbguest.no_install = true

  # ===== Update kernel-arm =====
  # Конфигурация виртуальной машины
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box = "generic/centos8"
    monitoring.vm.hostname = "monitoring"
    # monitoring.vm.network "private_network", ip: "192.168.56.13"
    monitoring.vm.network "forwarded_port", guest: 9090, host: 9090
    monitoring.vm.network "forwarded_port", guest: 3000, host: 3000
    monitoring.vm.network "forwarded_port", guest: 9100, host: 9100
    monitoring.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "monitoring"
    end

   # Выполняем послеустановочные скрипты
    monitoring.vm.provision "shell", inline: <<-SHELL
      dnf update -y
      dnf install -y wget curl nano tar grafana -y
      # Включаем автозапуск и запускаем службу
      systemctl daemon-reload
      systemctl start grafana-server
      systemctl enable grafana-server
    SHELL

    monitoring.vm.provision "shell",
    name: "Install Prometheus", 
    path: "scripts/install-prometheus.sh"
    
    monitoring.vm.provision "shell",
    name: "Install node_exporter.sh", 
    path: "scripts/install-node_exporter.sh"

  end
end