Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  
  # Отключить автоматическое обновление Guest Additions чтобы избежать проблем с репозиториями
  config.vbguest.auto_update = false

  # Исправить репозитории CentOS 7
  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/CentOS-*.repo
    sed -i 's/^#.*baseurl=http/baseurl=http/g' /etc/yum.repos.d/CentOS-*.repo
    sed -i 's/^mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/CentOS-*.repo
  SHELL

  # Ansible provisioner
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  # VM с nginx
  config.vm.define "nginx-server" do |web|
    web.vm.hostname = "nginx-server"
    web.vm.network "private_network", ip: "192.168.56.10"
    # Проброс порта для доступа с хоста
    web.vm.network "forwarded_port", guest: 8080, host: 8080
  end
end