Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "generic/rocky9"
  config.vm.box_check_update = false
  config.vbguest.no_install = true
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "web",
      :ip => "192.168.56.10",
    },
    { :name => "log",
      :ip => "192.168.56.15",
    }
  ]
  
  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
      
      # Ansible provision
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provisioning/playbook.yml"
        ansible.extra_vars = {
          node_name: opts[:name],
          node_ip: opts[:ip],
          log_server_ip: "192.168.56.15"
        }
      end
    end
  end
end